### ISSUE TITLE
请问网络训练时有使用额外的数据集或者其它训练技巧吗？

### ISSUE THREAD

**Issue by dongxiaoyi-xyz** [jinwan1994/SG-ShadowNet#2]
请问网络训练时有使用额外的数据集或者其它训练技巧吗？

**Comment by jinwan1994** [comment]
The details are described in the main paper.

**Comment by Jasonshao0123** [comment]
请问datasets.py中的train_mask50是怎么获取的呢？请问有处理的代码？或者处理好的数据集呢？

**Comment by Jasonshao0123** [comment]
> The details are described in the main paper.

请问datasets.py中的train_mask50是怎么获取的呢？请问有处理的代码？或者处理好的数据集呢？
